In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import os
import platform

In [ ]:
D:\Artificial Intelligence\Code Repository\External_Datasets_for_All_Projects\All_Projects_Implemented\Projects_for_Practice\Machine_Learning_Projects\Supervised_Learning_Projects\Regression_Projects\\train_BRCpofr.csv

In [3]:
#  Setting Path to Dataset
if platform.system().lower().__contains__('windows'):
    BASE_PATH_TO_CODE_REPOSITORY=(os.sep).join(os.getcwd().split(os.sep)[:os.getcwd().split(os.sep).index('Code Repository')+1])
    BASE_PATH_TO_DATASETS=os.path.join(BASE_PATH_TO_CODE_REPOSITORY,'External_Datasets_for_All_Projects')
    PROJECT_DIRECTORY_PATH=os.path.join(BASE_PATH_TO_DATASETS,'All_Projects_Implemented', 'Projects_for_Practice', 'Machine_Learning_Projects', 'Supervised_Learning_Projects','Regression_Projects')
    CURRENT_PROJECT_PATH=os.path.join(PROJECT_DIRECTORY_PATH,'Analytics_Jobathon_Insurance_projects')
elif platform.system().lower().__contains__('linux'):
    BASE_PATH_TO_CODE_REPOSITORY=(os.sep).join(os.getcwd().split(os.sep)[:os.getcwd().split(os.sep).index('Code Repository')+1])
    BASE_PATH_TO_DATASETS=os.path.join(BASE_PATH_TO_CODE_REPOSITORY,'External_Datasets_for_All_Projects')
    PROJECT_DIRECTORY_PATH=os.path.join(BASE_PATH_TO_DATASETS,'All_Projects_Implemented', 'Projects_for_Practice', 'Machine_Learning_Projects', 'Supervised_Learning_Projects','Regression_Projects')
    CURRENT_PROJECT_PATH=os.path.join(PROJECT_DIRECTORY_PATH,'Analytics_Jobathon_Insurance_projects')
    
else:
    print('OS Error')

In [5]:
CURRENT_TRAIN_DATA=os.path.join(CURRENT_PROJECT_PATH,'train_BRCpofr.csv')
CURRENT_TEST_DATA=os.path.join(CURRENT_PROJECT_PATH,'test_koRSKBP.csv')
# CURRENT_TRAIN_DATA=os.path.join(CURRENT_PROJECT_PATH,'train_BRCpofr.csv')

In [8]:
training_data=pd.read_csv(CURRENT_TRAIN_DATA)
test_data=pd.read_csv(CURRENT_TEST_DATA)

In [10]:
training_data

,id,gender,area,qualification,income,marital_status,vintage,claim_amount,num_policies,policy,type_of_policy,cltv
0,1,Male,Urban,Bachelor,5L-10L,1,5,5790,More than 1,A,Platinum,64308
1,2,Male,Rural,High School,5L-10L,0,8,5080,More than 1,A,Platinum,515400
2,3,Male,Urban,Bachelor,5L-10L,1,8,2599,More than 1,A,Platinum,64212
3,4,Female,Rural,High School,5L-10L,0,7,0,More than 1,A,Platinum,97920
4,5,Male,Urban,High School,More than 10L,1,6,3508,More than 1,A,Gold,59736
...,...,...,...,...,...,...,...,...,...,...,...,...
89387,89388,Male,Rural,High School,More than 10L,0,6,0,More than 1,B,Platinum,95736
89388,89389,Male,Urban,Bachelor,5L-10L,1,0,3897,More than 1,A,Platinum,67596
89389,89390,Female,Urban,Bachelor,5L-10L,0,4,3363,More than 1,B,Platinum,114120
89390,89391,Female,Rural,High School,2L-5L,0,8,0,More than 1,B,Platinum,71772
89391,89392,Female,Rural,High School,5L-10L,0,6,0,More than 1,B,Gold,108144